global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']  # Adjust if necessary

  - job_name: 'otel-collector'
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:9091']
